# Generated by Django 5.1.2 on 2024-10-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("busmap", "0003_alter_vehicalroute_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="balance",
            field=models.FloatField(default=0),
        ),
    ]
