# Generated by Django 5.1.2 on 2024-10-29 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("busmap", "0004_client_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="bankAccount",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="busmap.bankaccount"
            ),
        ),
    ]
